package com.cloud.modules.contract.entity;

import java.math.BigDecimal;
import java.util.Date;

public class contract {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_contract.contract_id
     *
     * @mbggenerated
     */
    private Integer contractId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_contract.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_contract.customer_id
     *
     * @mbggenerated
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_contract.business_id
     *
     * @mbggenerated
     */
    private Integer businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_contract.check_status
     *
     * @mbggenerated
     */
    private Integer checkStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_contract.examine_record_id
     *
     * @mbggenerated
     */
    private Integer examineRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_contract.order_date
     *
     * @mbggenerated
     */
    private Date orderDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_contract.create_user_id
     *
     * @mbggenerated
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_contract.owner_user_id
     *
     * @mbggenerated
     */
    private Long ownerUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_contract.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_contract.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_contract.num
     *
     * @mbggenerated
     */
    private String num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_contract.start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_contract.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_contract.money
     *
     * @mbggenerated
     */
    private BigDecimal money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_contract.discount_rate
     *
     * @mbggenerated
     */
    private BigDecimal discountRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_contract.total_price
     *
     * @mbggenerated
     */
    private BigDecimal totalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_contract.types
     *
     * @mbggenerated
     */
    private String types;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_contract.payment_type
     *
     * @mbggenerated
     */
    private String paymentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_contract.batch_id
     *
     * @mbggenerated
     */
    private String batchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_contract.ro_user_id
     *
     * @mbggenerated
     */
    private String roUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_contract.rw_user_id
     *
     * @mbggenerated
     */
    private String rwUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_contract.contacts_id
     *
     * @mbggenerated
     */
    private Integer contactsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_contract.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_contract.company_user_id
     *
     * @mbggenerated
     */
    private Integer companyUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_contract.contract_id
     *
     * @return the value of 72crm_crm_contract.contract_id
     *
     * @mbggenerated
     */
    public Integer getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_contract.contract_id
     *
     * @param contractId the value for 72crm_crm_contract.contract_id
     *
     * @mbggenerated
     */
    public void setContractId(Integer contractId) {
        this.contractId = contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_contract.name
     *
     * @return the value of 72crm_crm_contract.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_contract.name
     *
     * @param name the value for 72crm_crm_contract.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_contract.customer_id
     *
     * @return the value of 72crm_crm_contract.customer_id
     *
     * @mbggenerated
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_contract.customer_id
     *
     * @param customerId the value for 72crm_crm_contract.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_contract.business_id
     *
     * @return the value of 72crm_crm_contract.business_id
     *
     * @mbggenerated
     */
    public Integer getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_contract.business_id
     *
     * @param businessId the value for 72crm_crm_contract.business_id
     *
     * @mbggenerated
     */
    public void setBusinessId(Integer businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_contract.check_status
     *
     * @return the value of 72crm_crm_contract.check_status
     *
     * @mbggenerated
     */
    public Integer getCheckStatus() {
        return checkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_contract.check_status
     *
     * @param checkStatus the value for 72crm_crm_contract.check_status
     *
     * @mbggenerated
     */
    public void setCheckStatus(Integer checkStatus) {
        this.checkStatus = checkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_contract.examine_record_id
     *
     * @return the value of 72crm_crm_contract.examine_record_id
     *
     * @mbggenerated
     */
    public Integer getExamineRecordId() {
        return examineRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_contract.examine_record_id
     *
     * @param examineRecordId the value for 72crm_crm_contract.examine_record_id
     *
     * @mbggenerated
     */
    public void setExamineRecordId(Integer examineRecordId) {
        this.examineRecordId = examineRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_contract.order_date
     *
     * @return the value of 72crm_crm_contract.order_date
     *
     * @mbggenerated
     */
    public Date getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_contract.order_date
     *
     * @param orderDate the value for 72crm_crm_contract.order_date
     *
     * @mbggenerated
     */
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_contract.create_user_id
     *
     * @return the value of 72crm_crm_contract.create_user_id
     *
     * @mbggenerated
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_contract.create_user_id
     *
     * @param createUserId the value for 72crm_crm_contract.create_user_id
     *
     * @mbggenerated
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_contract.owner_user_id
     *
     * @return the value of 72crm_crm_contract.owner_user_id
     *
     * @mbggenerated
     */
    public Long getOwnerUserId() {
        return ownerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_contract.owner_user_id
     *
     * @param ownerUserId the value for 72crm_crm_contract.owner_user_id
     *
     * @mbggenerated
     */
    public void setOwnerUserId(Long ownerUserId) {
        this.ownerUserId = ownerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_contract.create_time
     *
     * @return the value of 72crm_crm_contract.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_contract.create_time
     *
     * @param createTime the value for 72crm_crm_contract.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_contract.update_time
     *
     * @return the value of 72crm_crm_contract.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_contract.update_time
     *
     * @param updateTime the value for 72crm_crm_contract.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_contract.num
     *
     * @return the value of 72crm_crm_contract.num
     *
     * @mbggenerated
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_contract.num
     *
     * @param num the value for 72crm_crm_contract.num
     *
     * @mbggenerated
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_contract.start_time
     *
     * @return the value of 72crm_crm_contract.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_contract.start_time
     *
     * @param startTime the value for 72crm_crm_contract.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_contract.end_time
     *
     * @return the value of 72crm_crm_contract.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_contract.end_time
     *
     * @param endTime the value for 72crm_crm_contract.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_contract.money
     *
     * @return the value of 72crm_crm_contract.money
     *
     * @mbggenerated
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_contract.money
     *
     * @param money the value for 72crm_crm_contract.money
     *
     * @mbggenerated
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_contract.discount_rate
     *
     * @return the value of 72crm_crm_contract.discount_rate
     *
     * @mbggenerated
     */
    public BigDecimal getDiscountRate() {
        return discountRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_contract.discount_rate
     *
     * @param discountRate the value for 72crm_crm_contract.discount_rate
     *
     * @mbggenerated
     */
    public void setDiscountRate(BigDecimal discountRate) {
        this.discountRate = discountRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_contract.total_price
     *
     * @return the value of 72crm_crm_contract.total_price
     *
     * @mbggenerated
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_contract.total_price
     *
     * @param totalPrice the value for 72crm_crm_contract.total_price
     *
     * @mbggenerated
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_contract.types
     *
     * @return the value of 72crm_crm_contract.types
     *
     * @mbggenerated
     */
    public String getTypes() {
        return types;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_contract.types
     *
     * @param types the value for 72crm_crm_contract.types
     *
     * @mbggenerated
     */
    public void setTypes(String types) {
        this.types = types == null ? null : types.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_contract.payment_type
     *
     * @return the value of 72crm_crm_contract.payment_type
     *
     * @mbggenerated
     */
    public String getPaymentType() {
        return paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_contract.payment_type
     *
     * @param paymentType the value for 72crm_crm_contract.payment_type
     *
     * @mbggenerated
     */
    public void setPaymentType(String paymentType) {
        this.paymentType = paymentType == null ? null : paymentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_contract.batch_id
     *
     * @return the value of 72crm_crm_contract.batch_id
     *
     * @mbggenerated
     */
    public String getBatchId() {
        return batchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_contract.batch_id
     *
     * @param batchId the value for 72crm_crm_contract.batch_id
     *
     * @mbggenerated
     */
    public void setBatchId(String batchId) {
        this.batchId = batchId == null ? null : batchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_contract.ro_user_id
     *
     * @return the value of 72crm_crm_contract.ro_user_id
     *
     * @mbggenerated
     */
    public String getRoUserId() {
        return roUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_contract.ro_user_id
     *
     * @param roUserId the value for 72crm_crm_contract.ro_user_id
     *
     * @mbggenerated
     */
    public void setRoUserId(String roUserId) {
        this.roUserId = roUserId == null ? null : roUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_contract.rw_user_id
     *
     * @return the value of 72crm_crm_contract.rw_user_id
     *
     * @mbggenerated
     */
    public String getRwUserId() {
        return rwUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_contract.rw_user_id
     *
     * @param rwUserId the value for 72crm_crm_contract.rw_user_id
     *
     * @mbggenerated
     */
    public void setRwUserId(String rwUserId) {
        this.rwUserId = rwUserId == null ? null : rwUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_contract.contacts_id
     *
     * @return the value of 72crm_crm_contract.contacts_id
     *
     * @mbggenerated
     */
    public Integer getContactsId() {
        return contactsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_contract.contacts_id
     *
     * @param contactsId the value for 72crm_crm_contract.contacts_id
     *
     * @mbggenerated
     */
    public void setContactsId(Integer contactsId) {
        this.contactsId = contactsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_contract.remark
     *
     * @return the value of 72crm_crm_contract.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_contract.remark
     *
     * @param remark the value for 72crm_crm_contract.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_contract.company_user_id
     *
     * @return the value of 72crm_crm_contract.company_user_id
     *
     * @mbggenerated
     */
    public Integer getCompanyUserId() {
        return companyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_contract.company_user_id
     *
     * @param companyUserId the value for 72crm_crm_contract.company_user_id
     *
     * @mbggenerated
     */
    public void setCompanyUserId(Integer companyUserId) {
        this.companyUserId = companyUserId;
    }
}