package com.cloud.modules.business.dao;

import com.cloud.modules.business.entity.business;
import com.cloud.modules.business.entity.businessExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Mapper
@Component
public interface businessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_business
     *
     * @mbggenerated
     */
    int countByExample(businessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_business
     *
     * @mbggenerated
     */
    int deleteByExample(businessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_business
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer businessId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_business
     *
     * @mbggenerated
     */
    int insert(business record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_business
     *
     * @mbggenerated
     */
    int insertSelective(business record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_business
     *
     * @mbggenerated
     */
    List<business> selectByExample(businessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_business
     *
     * @mbggenerated
     */
    business selectByPrimaryKey(Integer businessId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_business
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") business record, @Param("example") businessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_business
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") business record, @Param("example") businessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_business
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(business record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_business
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(business record);
}