package com.cloud.modules.crm.dao;

import com.cloud.modules.crm.entity.contacts;
import com.cloud.modules.crm.entity.contactsExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Mapper
@Component
public interface contactsMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_contacts
     *
     * @mbggenerated
     */
    int countByExample(contactsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_contacts
     *
     * @mbggenerated
     */
    int deleteByExample(contactsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_contacts
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer contactsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_contacts
     *
     * @mbggenerated
     */
    int insert(contacts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_contacts
     *
     * @mbggenerated
     */
    int insertSelective(contacts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_contacts
     *
     * @mbggenerated
     */
    List<contacts> selectByExample(contactsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_contacts
     *
     * @mbggenerated
     */
    contacts selectByPrimaryKey(Integer contactsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_contacts
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") contacts record, @Param("example") contactsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_contacts
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") contacts record, @Param("example") contactsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_contacts
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(contacts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_contacts
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(contacts record);
}