package com.cloud.modules.crm.dao;

import com.cloud.modules.crm.entity.leads;
import com.cloud.modules.crm.entity.leadsExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Mapper
@Component
public interface leadsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_leads
     *
     * @mbggenerated
     */
    int countByExample(leadsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_leads
     *
     * @mbggenerated
     */
    int deleteByExample(leadsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_leads
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer leadsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_leads
     *
     * @mbggenerated
     */
    int insert(leads record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_leads
     *
     * @mbggenerated
     */
    int insertSelective(leads record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_leads
     *
     * @mbggenerated
     */
    List<leads> selectByExample(leadsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_leads
     *
     * @mbggenerated
     */
    leads selectByPrimaryKey(Integer leadsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_leads
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") leads record, @Param("example") leadsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_leads
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") leads record, @Param("example") leadsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_leads
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(leads record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_leads
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(leads record);
}