package com.cloud.modules.product.dao;

import com.cloud.modules.product.entity.product;
import com.cloud.modules.product.entity.productExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Mapper
@Component
public interface productMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_product
     *
     * @mbggenerated
     */
    int countByExample(productExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_product
     *
     * @mbggenerated
     */
    int deleteByExample(productExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_product
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_product
     *
     * @mbggenerated
     */
    int insert(product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_product
     *
     * @mbggenerated
     */
    int insertSelective(product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_product
     *
     * @mbggenerated
     */
    List<product> selectByExampleWithBLOBs(productExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_product
     *
     * @mbggenerated
     */
    List<product> selectByExample(productExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_product
     *
     * @mbggenerated
     */
    product selectByPrimaryKey(Integer productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_product
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") product record, @Param("example") productExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_product
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") product record, @Param("example") productExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_product
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") product record, @Param("example") productExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(product record);
}