package com.cloud.modules.receivables.entity;

import java.util.Date;

public class receivables {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_receivables.receivables_id
     *
     * @mbggenerated
     */
    private Integer receivablesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_receivables.number
     *
     * @mbggenerated
     */
    private String number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_receivables.plan_id
     *
     * @mbggenerated
     */
    private Integer planId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_receivables.customer_id
     *
     * @mbggenerated
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_receivables.contract_id
     *
     * @mbggenerated
     */
    private Integer contractId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_receivables.check_status
     *
     * @mbggenerated
     */
    private Integer checkStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_receivables.examine_record_id
     *
     * @mbggenerated
     */
    private Integer examineRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_receivables.return_time
     *
     * @mbggenerated
     */
    private String returnTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_receivables.return_type
     *
     * @mbggenerated
     */
    private String returnType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_receivables.money
     *
     * @mbggenerated
     */
    private String money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_receivables.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_receivables.create_user_id
     *
     * @mbggenerated
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_receivables.owner_user_id
     *
     * @mbggenerated
     */
    private Long ownerUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_receivables.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_receivables.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_receivables.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_receivables.batch_id
     *
     * @mbggenerated
     */
    private String batchId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_receivables.receivables_id
     *
     * @return the value of 72crm_crm_receivables.receivables_id
     *
     * @mbggenerated
     */
    public Integer getReceivablesId() {
        return receivablesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_receivables.receivables_id
     *
     * @param receivablesId the value for 72crm_crm_receivables.receivables_id
     *
     * @mbggenerated
     */
    public void setReceivablesId(Integer receivablesId) {
        this.receivablesId = receivablesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_receivables.number
     *
     * @return the value of 72crm_crm_receivables.number
     *
     * @mbggenerated
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_receivables.number
     *
     * @param number the value for 72crm_crm_receivables.number
     *
     * @mbggenerated
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_receivables.plan_id
     *
     * @return the value of 72crm_crm_receivables.plan_id
     *
     * @mbggenerated
     */
    public Integer getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_receivables.plan_id
     *
     * @param planId the value for 72crm_crm_receivables.plan_id
     *
     * @mbggenerated
     */
    public void setPlanId(Integer planId) {
        this.planId = planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_receivables.customer_id
     *
     * @return the value of 72crm_crm_receivables.customer_id
     *
     * @mbggenerated
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_receivables.customer_id
     *
     * @param customerId the value for 72crm_crm_receivables.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_receivables.contract_id
     *
     * @return the value of 72crm_crm_receivables.contract_id
     *
     * @mbggenerated
     */
    public Integer getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_receivables.contract_id
     *
     * @param contractId the value for 72crm_crm_receivables.contract_id
     *
     * @mbggenerated
     */
    public void setContractId(Integer contractId) {
        this.contractId = contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_receivables.check_status
     *
     * @return the value of 72crm_crm_receivables.check_status
     *
     * @mbggenerated
     */
    public Integer getCheckStatus() {
        return checkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_receivables.check_status
     *
     * @param checkStatus the value for 72crm_crm_receivables.check_status
     *
     * @mbggenerated
     */
    public void setCheckStatus(Integer checkStatus) {
        this.checkStatus = checkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_receivables.examine_record_id
     *
     * @return the value of 72crm_crm_receivables.examine_record_id
     *
     * @mbggenerated
     */
    public Integer getExamineRecordId() {
        return examineRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_receivables.examine_record_id
     *
     * @param examineRecordId the value for 72crm_crm_receivables.examine_record_id
     *
     * @mbggenerated
     */
    public void setExamineRecordId(Integer examineRecordId) {
        this.examineRecordId = examineRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_receivables.return_time
     *
     * @return the value of 72crm_crm_receivables.return_time
     *
     * @mbggenerated
     */
    public String getReturnTime() {
        return returnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_receivables.return_time
     *
     * @param returnTime the value for 72crm_crm_receivables.return_time
     *
     * @mbggenerated
     */
    public void setReturnTime(String returnTime) {
        this.returnTime = returnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_receivables.return_type
     *
     * @return the value of 72crm_crm_receivables.return_type
     *
     * @mbggenerated
     */
    public String getReturnType() {
        return returnType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_receivables.return_type
     *
     * @param returnType the value for 72crm_crm_receivables.return_type
     *
     * @mbggenerated
     */
    public void setReturnType(String returnType) {
        this.returnType = returnType == null ? null : returnType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_receivables.money
     *
     * @return the value of 72crm_crm_receivables.money
     *
     * @mbggenerated
     */
    public String getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_receivables.money
     *
     * @param money the value for 72crm_crm_receivables.money
     *
     * @mbggenerated
     */
    public void setMoney(String money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_receivables.remark
     *
     * @return the value of 72crm_crm_receivables.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_receivables.remark
     *
     * @param remark the value for 72crm_crm_receivables.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_receivables.create_user_id
     *
     * @return the value of 72crm_crm_receivables.create_user_id
     *
     * @mbggenerated
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_receivables.create_user_id
     *
     * @param createUserId the value for 72crm_crm_receivables.create_user_id
     *
     * @mbggenerated
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_receivables.owner_user_id
     *
     * @return the value of 72crm_crm_receivables.owner_user_id
     *
     * @mbggenerated
     */
    public Long getOwnerUserId() {
        return ownerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_receivables.owner_user_id
     *
     * @param ownerUserId the value for 72crm_crm_receivables.owner_user_id
     *
     * @mbggenerated
     */
    public void setOwnerUserId(Long ownerUserId) {
        this.ownerUserId = ownerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_receivables.create_time
     *
     * @return the value of 72crm_crm_receivables.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_receivables.create_time
     *
     * @param createTime the value for 72crm_crm_receivables.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_receivables.update_time
     *
     * @return the value of 72crm_crm_receivables.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_receivables.update_time
     *
     * @param updateTime the value for 72crm_crm_receivables.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_receivables.remarks
     *
     * @return the value of 72crm_crm_receivables.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_receivables.remarks
     *
     * @param remarks the value for 72crm_crm_receivables.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_receivables.batch_id
     *
     * @return the value of 72crm_crm_receivables.batch_id
     *
     * @mbggenerated
     */
    public String getBatchId() {
        return batchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_receivables.batch_id
     *
     * @param batchId the value for 72crm_crm_receivables.batch_id
     *
     * @mbggenerated
     */
    public void setBatchId(String batchId) {
        this.batchId = batchId == null ? null : batchId.trim();
    }
}