package com.cloud.modules.business.entity;

import java.math.BigDecimal;
import java.util.Date;

public class business {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_business.business_id
     *
     * @mbggenerated
     */
    private Integer businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_business.type_id
     *
     * @mbggenerated
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_business.status_id
     *
     * @mbggenerated
     */
    private Integer statusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_business.next_time
     *
     * @mbggenerated
     */
    private Date nextTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_business.customer_id
     *
     * @mbggenerated
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_business.deal_date
     *
     * @mbggenerated
     */
    private String dealDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_business.business_name
     *
     * @mbggenerated
     */
    private String businessName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_business.money
     *
     * @mbggenerated
     */
    private BigDecimal money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_business.discount_rate
     *
     * @mbggenerated
     */
    private BigDecimal discountRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_business.total_price
     *
     * @mbggenerated
     */
    private BigDecimal totalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_business.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_business.create_user_id
     *
     * @mbggenerated
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_business.owner_user_id
     *
     * @mbggenerated
     */
    private Long ownerUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_business.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_business.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_business.batch_id
     *
     * @mbggenerated
     */
    private String batchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_business.ro_user_id
     *
     * @mbggenerated
     */
    private String roUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_business.rw_user_id
     *
     * @mbggenerated
     */
    private String rwUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_business.is_end
     *
     * @mbggenerated
     */
    private Integer isEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_business.status_remark
     *
     * @mbggenerated
     */
    private String statusRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_business.business_id
     *
     * @return the value of 72crm_crm_business.business_id
     *
     * @mbggenerated
     */
    public Integer getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_business.business_id
     *
     * @param businessId the value for 72crm_crm_business.business_id
     *
     * @mbggenerated
     */
    public void setBusinessId(Integer businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_business.type_id
     *
     * @return the value of 72crm_crm_business.type_id
     *
     * @mbggenerated
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_business.type_id
     *
     * @param typeId the value for 72crm_crm_business.type_id
     *
     * @mbggenerated
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_business.status_id
     *
     * @return the value of 72crm_crm_business.status_id
     *
     * @mbggenerated
     */
    public Integer getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_business.status_id
     *
     * @param statusId the value for 72crm_crm_business.status_id
     *
     * @mbggenerated
     */
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_business.next_time
     *
     * @return the value of 72crm_crm_business.next_time
     *
     * @mbggenerated
     */
    public Date getNextTime() {
        return nextTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_business.next_time
     *
     * @param nextTime the value for 72crm_crm_business.next_time
     *
     * @mbggenerated
     */
    public void setNextTime(Date nextTime) {
        this.nextTime = nextTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_business.customer_id
     *
     * @return the value of 72crm_crm_business.customer_id
     *
     * @mbggenerated
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_business.customer_id
     *
     * @param customerId the value for 72crm_crm_business.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_business.deal_date
     *
     * @return the value of 72crm_crm_business.deal_date
     *
     * @mbggenerated
     */
    public String getDealDate() {
        return dealDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_business.deal_date
     *
     * @param dealDate the value for 72crm_crm_business.deal_date
     *
     * @mbggenerated
     */
    public void setDealDate(String dealDate) {
        this.dealDate = dealDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_business.business_name
     *
     * @return the value of 72crm_crm_business.business_name
     *
     * @mbggenerated
     */
    public String getBusinessName() {
        return businessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_business.business_name
     *
     * @param businessName the value for 72crm_crm_business.business_name
     *
     * @mbggenerated
     */
    public void setBusinessName(String businessName) {
        this.businessName = businessName == null ? null : businessName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_business.money
     *
     * @return the value of 72crm_crm_business.money
     *
     * @mbggenerated
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_business.money
     *
     * @param money the value for 72crm_crm_business.money
     *
     * @mbggenerated
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_business.discount_rate
     *
     * @return the value of 72crm_crm_business.discount_rate
     *
     * @mbggenerated
     */
    public BigDecimal getDiscountRate() {
        return discountRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_business.discount_rate
     *
     * @param discountRate the value for 72crm_crm_business.discount_rate
     *
     * @mbggenerated
     */
    public void setDiscountRate(BigDecimal discountRate) {
        this.discountRate = discountRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_business.total_price
     *
     * @return the value of 72crm_crm_business.total_price
     *
     * @mbggenerated
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_business.total_price
     *
     * @param totalPrice the value for 72crm_crm_business.total_price
     *
     * @mbggenerated
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_business.remark
     *
     * @return the value of 72crm_crm_business.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_business.remark
     *
     * @param remark the value for 72crm_crm_business.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_business.create_user_id
     *
     * @return the value of 72crm_crm_business.create_user_id
     *
     * @mbggenerated
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_business.create_user_id
     *
     * @param createUserId the value for 72crm_crm_business.create_user_id
     *
     * @mbggenerated
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_business.owner_user_id
     *
     * @return the value of 72crm_crm_business.owner_user_id
     *
     * @mbggenerated
     */
    public Long getOwnerUserId() {
        return ownerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_business.owner_user_id
     *
     * @param ownerUserId the value for 72crm_crm_business.owner_user_id
     *
     * @mbggenerated
     */
    public void setOwnerUserId(Long ownerUserId) {
        this.ownerUserId = ownerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_business.create_time
     *
     * @return the value of 72crm_crm_business.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_business.create_time
     *
     * @param createTime the value for 72crm_crm_business.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_business.update_time
     *
     * @return the value of 72crm_crm_business.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_business.update_time
     *
     * @param updateTime the value for 72crm_crm_business.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_business.batch_id
     *
     * @return the value of 72crm_crm_business.batch_id
     *
     * @mbggenerated
     */
    public String getBatchId() {
        return batchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_business.batch_id
     *
     * @param batchId the value for 72crm_crm_business.batch_id
     *
     * @mbggenerated
     */
    public void setBatchId(String batchId) {
        this.batchId = batchId == null ? null : batchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_business.ro_user_id
     *
     * @return the value of 72crm_crm_business.ro_user_id
     *
     * @mbggenerated
     */
    public String getRoUserId() {
        return roUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_business.ro_user_id
     *
     * @param roUserId the value for 72crm_crm_business.ro_user_id
     *
     * @mbggenerated
     */
    public void setRoUserId(String roUserId) {
        this.roUserId = roUserId == null ? null : roUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_business.rw_user_id
     *
     * @return the value of 72crm_crm_business.rw_user_id
     *
     * @mbggenerated
     */
    public String getRwUserId() {
        return rwUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_business.rw_user_id
     *
     * @param rwUserId the value for 72crm_crm_business.rw_user_id
     *
     * @mbggenerated
     */
    public void setRwUserId(String rwUserId) {
        this.rwUserId = rwUserId == null ? null : rwUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_business.is_end
     *
     * @return the value of 72crm_crm_business.is_end
     *
     * @mbggenerated
     */
    public Integer getIsEnd() {
        return isEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_business.is_end
     *
     * @param isEnd the value for 72crm_crm_business.is_end
     *
     * @mbggenerated
     */
    public void setIsEnd(Integer isEnd) {
        this.isEnd = isEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_business.status_remark
     *
     * @return the value of 72crm_crm_business.status_remark
     *
     * @mbggenerated
     */
    public String getStatusRemark() {
        return statusRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_business.status_remark
     *
     * @param statusRemark the value for 72crm_crm_business.status_remark
     *
     * @mbggenerated
     */
    public void setStatusRemark(String statusRemark) {
        this.statusRemark = statusRemark == null ? null : statusRemark.trim();
    }
}