package com.cloud.modules.crm.entity;

import lombok.Data;

import javax.persistence.Table;
import java.util.Date;

@Data
@Table(name = "72crm_crm_leads")
public class crm_leadsEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_leads.leads_id
     *
     * @mbggenerated
     */
    private Integer leadsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_leads.is_transform
     *
     * @mbggenerated
     */
    private Integer isTransform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_leads.followup
     *
     * @mbggenerated
     */
    private Integer followup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_leads.leads_name
     *
     * @mbggenerated
     */
    private String leadsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_leads.customer_id
     *
     * @mbggenerated
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_leads.next_time
     *
     * @mbggenerated
     */
    private Date nextTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_leads.telephone
     *
     * @mbggenerated
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_leads.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_leads.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_leads.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_leads.create_user_id
     *
     * @mbggenerated
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_leads.owner_user_id
     *
     * @mbggenerated
     */
    private Long ownerUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_leads.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_leads.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_leads.batch_id
     *
     * @mbggenerated
     */
    private String batchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_leads.last_content
     *
     * @mbggenerated
     */
    private String lastContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_leads.leads_id
     *
     * @return the value of 72crm_crm_leads.leads_id
     *
     * @mbggenerated
     */
    public Integer getLeadsId() {
        return leadsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_leads.leads_id
     *
     * @param leadsId the value for 72crm_crm_leads.leads_id
     *
     * @mbggenerated
     */
    public void setLeadsId(Integer leadsId) {
        this.leadsId = leadsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_leads.is_transform
     *
     * @return the value of 72crm_crm_leads.is_transform
     *
     * @mbggenerated
     */
    public Integer getIsTransform() {
        return isTransform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_leads.is_transform
     *
     * @param isTransform the value for 72crm_crm_leads.is_transform
     *
     * @mbggenerated
     */
    public void setIsTransform(Integer isTransform) {
        this.isTransform = isTransform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_leads.followup
     *
     * @return the value of 72crm_crm_leads.followup
     *
     * @mbggenerated
     */
    public Integer getFollowup() {
        return followup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_leads.followup
     *
     * @param followup the value for 72crm_crm_leads.followup
     *
     * @mbggenerated
     */
    public void setFollowup(Integer followup) {
        this.followup = followup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_leads.leads_name
     *
     * @return the value of 72crm_crm_leads.leads_name
     *
     * @mbggenerated
     */
    public String getLeadsName() {
        return leadsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_leads.leads_name
     *
     * @param leadsName the value for 72crm_crm_leads.leads_name
     *
     * @mbggenerated
     */
    public void setLeadsName(String leadsName) {
        this.leadsName = leadsName == null ? null : leadsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_leads.customer_id
     *
     * @return the value of 72crm_crm_leads.customer_id
     *
     * @mbggenerated
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_leads.customer_id
     *
     * @param customerId the value for 72crm_crm_leads.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_leads.next_time
     *
     * @return the value of 72crm_crm_leads.next_time
     *
     * @mbggenerated
     */
    public Date getNextTime() {
        return nextTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_leads.next_time
     *
     * @param nextTime the value for 72crm_crm_leads.next_time
     *
     * @mbggenerated
     */
    public void setNextTime(Date nextTime) {
        this.nextTime = nextTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_leads.telephone
     *
     * @return the value of 72crm_crm_leads.telephone
     *
     * @mbggenerated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_leads.telephone
     *
     * @param telephone the value for 72crm_crm_leads.telephone
     *
     * @mbggenerated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_leads.mobile
     *
     * @return the value of 72crm_crm_leads.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_leads.mobile
     *
     * @param mobile the value for 72crm_crm_leads.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_leads.address
     *
     * @return the value of 72crm_crm_leads.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_leads.address
     *
     * @param address the value for 72crm_crm_leads.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_leads.remark
     *
     * @return the value of 72crm_crm_leads.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_leads.remark
     *
     * @param remark the value for 72crm_crm_leads.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_leads.create_user_id
     *
     * @return the value of 72crm_crm_leads.create_user_id
     *
     * @mbggenerated
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_leads.create_user_id
     *
     * @param createUserId the value for 72crm_crm_leads.create_user_id
     *
     * @mbggenerated
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_leads.owner_user_id
     *
     * @return the value of 72crm_crm_leads.owner_user_id
     *
     * @mbggenerated
     */
    public Long getOwnerUserId() {
        return ownerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_leads.owner_user_id
     *
     * @param ownerUserId the value for 72crm_crm_leads.owner_user_id
     *
     * @mbggenerated
     */
    public void setOwnerUserId(Long ownerUserId) {
        this.ownerUserId = ownerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_leads.create_time
     *
     * @return the value of 72crm_crm_leads.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_leads.create_time
     *
     * @param createTime the value for 72crm_crm_leads.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_leads.update_time
     *
     * @return the value of 72crm_crm_leads.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_leads.update_time
     *
     * @param updateTime the value for 72crm_crm_leads.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_leads.batch_id
     *
     * @return the value of 72crm_crm_leads.batch_id
     *
     * @mbggenerated
     */
    public String getBatchId() {
        return batchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_leads.batch_id
     *
     * @param batchId the value for 72crm_crm_leads.batch_id
     *
     * @mbggenerated
     */
    public void setBatchId(String batchId) {
        this.batchId = batchId == null ? null : batchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_leads.last_content
     *
     * @return the value of 72crm_crm_leads.last_content
     *
     * @mbggenerated
     */
    public String getLastContent() {
        return lastContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_leads.last_content
     *
     * @param lastContent the value for 72crm_crm_leads.last_content
     *
     * @mbggenerated
     */
    public void setLastContent(String lastContent) {
        this.lastContent = lastContent == null ? null : lastContent.trim();
    }
}