package com.cloud.modules.product.entity;

import java.math.BigDecimal;
import java.util.Date;

public class product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_product.product_id
     *
     * @mbggenerated
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_product.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_product.num
     *
     * @mbggenerated
     */
    private String num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_product.unit
     *
     * @mbggenerated
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_product.price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_product.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_product.category_id
     *
     * @mbggenerated
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_product.create_user_id
     *
     * @mbggenerated
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_product.owner_user_id
     *
     * @mbggenerated
     */
    private Long ownerUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_product.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_product.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_product.batch_id
     *
     * @mbggenerated
     */
    private String batchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_crm_product.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_product.product_id
     *
     * @return the value of 72crm_crm_product.product_id
     *
     * @mbggenerated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_product.product_id
     *
     * @param productId the value for 72crm_crm_product.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_product.name
     *
     * @return the value of 72crm_crm_product.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_product.name
     *
     * @param name the value for 72crm_crm_product.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_product.num
     *
     * @return the value of 72crm_crm_product.num
     *
     * @mbggenerated
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_product.num
     *
     * @param num the value for 72crm_crm_product.num
     *
     * @mbggenerated
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_product.unit
     *
     * @return the value of 72crm_crm_product.unit
     *
     * @mbggenerated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_product.unit
     *
     * @param unit the value for 72crm_crm_product.unit
     *
     * @mbggenerated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_product.price
     *
     * @return the value of 72crm_crm_product.price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_product.price
     *
     * @param price the value for 72crm_crm_product.price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_product.status
     *
     * @return the value of 72crm_crm_product.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_product.status
     *
     * @param status the value for 72crm_crm_product.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_product.category_id
     *
     * @return the value of 72crm_crm_product.category_id
     *
     * @mbggenerated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_product.category_id
     *
     * @param categoryId the value for 72crm_crm_product.category_id
     *
     * @mbggenerated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_product.create_user_id
     *
     * @return the value of 72crm_crm_product.create_user_id
     *
     * @mbggenerated
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_product.create_user_id
     *
     * @param createUserId the value for 72crm_crm_product.create_user_id
     *
     * @mbggenerated
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_product.owner_user_id
     *
     * @return the value of 72crm_crm_product.owner_user_id
     *
     * @mbggenerated
     */
    public Long getOwnerUserId() {
        return ownerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_product.owner_user_id
     *
     * @param ownerUserId the value for 72crm_crm_product.owner_user_id
     *
     * @mbggenerated
     */
    public void setOwnerUserId(Long ownerUserId) {
        this.ownerUserId = ownerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_product.create_time
     *
     * @return the value of 72crm_crm_product.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_product.create_time
     *
     * @param createTime the value for 72crm_crm_product.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_product.update_time
     *
     * @return the value of 72crm_crm_product.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_product.update_time
     *
     * @param updateTime the value for 72crm_crm_product.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_product.batch_id
     *
     * @return the value of 72crm_crm_product.batch_id
     *
     * @mbggenerated
     */
    public String getBatchId() {
        return batchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_product.batch_id
     *
     * @param batchId the value for 72crm_crm_product.batch_id
     *
     * @mbggenerated
     */
    public void setBatchId(String batchId) {
        this.batchId = batchId == null ? null : batchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_crm_product.description
     *
     * @return the value of 72crm_crm_product.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_crm_product.description
     *
     * @param description the value for 72crm_crm_product.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}