package com.cloud.modules.contract.dao;

import com.cloud.modules.contract.entity.contract;
import com.cloud.modules.contract.entity.contractExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Mapper
@Component
public interface contractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_contract
     *
     * @mbggenerated
     */
    int countByExample(contractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_contract
     *
     * @mbggenerated
     */
    int deleteByExample(contractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_contract
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer contractId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_contract
     *
     * @mbggenerated
     */
    int insert(contract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_contract
     *
     * @mbggenerated
     */
    int insertSelective(contract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_contract
     *
     * @mbggenerated
     */
    List<contract> selectByExample(contractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_contract
     *
     * @mbggenerated
     */
    contract selectByPrimaryKey(Integer contractId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_contract
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") contract record, @Param("example") contractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_contract
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") contract record, @Param("example") contractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_contract
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(contract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_contract
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(contract record);
}