package com.cloud.modules.message.dao;

import com.cloud.modules.message.entity.message;
import com.cloud.modules.message.entity.messageExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Mapper
@Component
public interface messageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_admin_message
     *
     * @mbggenerated
     */
    int countByExample(messageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_admin_message
     *
     * @mbggenerated
     */
    int deleteByExample(messageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_admin_message
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long messageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_admin_message
     *
     * @mbggenerated
     */
    int insert(message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_admin_message
     *
     * @mbggenerated
     */
    int insertSelective(message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_admin_message
     *
     * @mbggenerated
     */
    List<message> selectByExample(messageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_admin_message
     *
     * @mbggenerated
     */
    message selectByPrimaryKey(Long messageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_admin_message
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") message record, @Param("example") messageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_admin_message
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") message record, @Param("example") messageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_admin_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_admin_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(message record);
}