package com.cloud.modules.record.entity;

import java.util.Date;

public class record {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_admin_record.record_id
     *
     * @mbggenerated
     */
    private Integer recordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_admin_record.types
     *
     * @mbggenerated
     */
    private String types;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_admin_record.types_id
     *
     * @mbggenerated
     */
    private Integer typesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_admin_record.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_admin_record.category
     *
     * @mbggenerated
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_admin_record.next_time
     *
     * @mbggenerated
     */
    private Date nextTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_admin_record.business_ids
     *
     * @mbggenerated
     */
    private String businessIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_admin_record.contacts_ids
     *
     * @mbggenerated
     */
    private String contactsIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_admin_record.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_admin_record.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_admin_record.create_user_id
     *
     * @mbggenerated
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 72crm_admin_record.batch_id
     *
     * @mbggenerated
     */
    private String batchId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_admin_record.record_id
     *
     * @return the value of 72crm_admin_record.record_id
     *
     * @mbggenerated
     */
    public Integer getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_admin_record.record_id
     *
     * @param recordId the value for 72crm_admin_record.record_id
     *
     * @mbggenerated
     */
    public void setRecordId(Integer recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_admin_record.types
     *
     * @return the value of 72crm_admin_record.types
     *
     * @mbggenerated
     */
    public String getTypes() {
        return types;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_admin_record.types
     *
     * @param types the value for 72crm_admin_record.types
     *
     * @mbggenerated
     */
    public void setTypes(String types) {
        this.types = types == null ? null : types.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_admin_record.types_id
     *
     * @return the value of 72crm_admin_record.types_id
     *
     * @mbggenerated
     */
    public Integer getTypesId() {
        return typesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_admin_record.types_id
     *
     * @param typesId the value for 72crm_admin_record.types_id
     *
     * @mbggenerated
     */
    public void setTypesId(Integer typesId) {
        this.typesId = typesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_admin_record.content
     *
     * @return the value of 72crm_admin_record.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_admin_record.content
     *
     * @param content the value for 72crm_admin_record.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_admin_record.category
     *
     * @return the value of 72crm_admin_record.category
     *
     * @mbggenerated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_admin_record.category
     *
     * @param category the value for 72crm_admin_record.category
     *
     * @mbggenerated
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_admin_record.next_time
     *
     * @return the value of 72crm_admin_record.next_time
     *
     * @mbggenerated
     */
    public Date getNextTime() {
        return nextTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_admin_record.next_time
     *
     * @param nextTime the value for 72crm_admin_record.next_time
     *
     * @mbggenerated
     */
    public void setNextTime(Date nextTime) {
        this.nextTime = nextTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_admin_record.business_ids
     *
     * @return the value of 72crm_admin_record.business_ids
     *
     * @mbggenerated
     */
    public String getBusinessIds() {
        return businessIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_admin_record.business_ids
     *
     * @param businessIds the value for 72crm_admin_record.business_ids
     *
     * @mbggenerated
     */
    public void setBusinessIds(String businessIds) {
        this.businessIds = businessIds == null ? null : businessIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_admin_record.contacts_ids
     *
     * @return the value of 72crm_admin_record.contacts_ids
     *
     * @mbggenerated
     */
    public String getContactsIds() {
        return contactsIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_admin_record.contacts_ids
     *
     * @param contactsIds the value for 72crm_admin_record.contacts_ids
     *
     * @mbggenerated
     */
    public void setContactsIds(String contactsIds) {
        this.contactsIds = contactsIds == null ? null : contactsIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_admin_record.create_time
     *
     * @return the value of 72crm_admin_record.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_admin_record.create_time
     *
     * @param createTime the value for 72crm_admin_record.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_admin_record.update_time
     *
     * @return the value of 72crm_admin_record.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_admin_record.update_time
     *
     * @param updateTime the value for 72crm_admin_record.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_admin_record.create_user_id
     *
     * @return the value of 72crm_admin_record.create_user_id
     *
     * @mbggenerated
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_admin_record.create_user_id
     *
     * @param createUserId the value for 72crm_admin_record.create_user_id
     *
     * @mbggenerated
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 72crm_admin_record.batch_id
     *
     * @return the value of 72crm_admin_record.batch_id
     *
     * @mbggenerated
     */
    public String getBatchId() {
        return batchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 72crm_admin_record.batch_id
     *
     * @param batchId the value for 72crm_admin_record.batch_id
     *
     * @mbggenerated
     */
    public void setBatchId(String batchId) {
        this.batchId = batchId == null ? null : batchId.trim();
    }
}