package com.cloud.modules.receivables.dao;

import com.cloud.modules.receivables.entity.receivables;
import com.cloud.modules.receivables.entity.receivablesExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
@Mapper
public interface receivablesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_receivables
     *
     * @mbggenerated
     */
    int countByExample(receivablesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_receivables
     *
     * @mbggenerated
     */
    int deleteByExample(receivablesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_receivables
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer receivablesId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_receivables
     *
     * @mbggenerated
     */
    int insert(receivables record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_receivables
     *
     * @mbggenerated
     */
    int insertSelective(receivables record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_receivables
     *
     * @mbggenerated
     */
    List<receivables> selectByExample(receivablesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_receivables
     *
     * @mbggenerated
     */
    receivables selectByPrimaryKey(Integer receivablesId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_receivables
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") receivables record, @Param("example") receivablesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_receivables
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") receivables record, @Param("example") receivablesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_receivables
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(receivables record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_receivables
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(receivables record);
}