package com.cloud.modules.dept.dao;

import com.cloud.modules.dept.entity.dept;
import com.cloud.modules.dept.entity.deptExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.beans.factory.annotation.Autowired;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

@Component
@Mapper
public interface deptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_admin_dept
     *
     * @mbggenerated
     */
    int countByExample(deptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_admin_dept
     *
     * @mbggenerated
     */
    int deleteByExample(deptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_admin_dept
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_admin_dept
     *
     * @mbggenerated
     */
    int insert(dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_admin_dept
     *
     * @mbggenerated
     */
    int insertSelective(dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_admin_dept
     *
     * @mbggenerated
     */
    List<dept> selectByExample(deptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_admin_dept
     *
     * @mbggenerated
     */
    dept selectByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_admin_dept
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") dept record, @Param("example") deptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_admin_dept
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") dept record, @Param("example") deptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_admin_dept
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_admin_dept
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(dept record);
}