package com.cloud.modules.customer.dao;

import com.cloud.modules.customer.entity.customer;
import com.cloud.modules.customer.entity.customerExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Mapper
@Component
public interface customerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_customer
     *
     * @mbggenerated
     */
    int countByExample(customerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_customer
     *
     * @mbggenerated
     */
    int deleteByExample(customerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_customer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer customerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_customer
     *
     * @mbggenerated
     */
    int insert(customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_customer
     *
     * @mbggenerated
     */
    int insertSelective(customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_customer
     *
     * @mbggenerated
     */
    List<customer> selectByExample(customerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_customer
     *
     * @mbggenerated
     */
    customer selectByPrimaryKey(Integer customerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_customer
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") customer record, @Param("example") customerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_customer
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") customer record, @Param("example") customerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_customer
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 72crm_crm_customer
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(customer record);
}